# Generated by Django 2.0.9 on 2018-10-30 20:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cab_driver_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_start_time', models.DateTimeField(null=True)),
                ('ride_end_time', models.DateTimeField(null=True)),
                ('source_address', models.CharField(max_length=100)),
                ('source_position', geoposition.fields.GeopositionField(max_length=42)),
                ('destination_address', models.CharField(max_length=100)),
                ('destination_position', geoposition.fields.GeopositionField(max_length=42)),
                ('cancelled', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('payment_type_id', models.IntegerField()),
                ('cancellation_reason', models.CharField(max_length=500, null=True)),
                ('user_ride_complaint', models.CharField(max_length=500, null=True)),
                ('driver_ride_complaint', models.CharField(max_length=500, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_driver_app.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='CabRideStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('status_timestamp', models.DateTimeField()),
                ('status_details', models.CharField(max_length=100)),
                ('cab_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_user_app.CabRide')),
            ],
        ),
        migrations.CreateModel(
            name='CabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('rating', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('total_rides', models.IntegerField()),
            ],
        ),
    ]
